---
title: "Using `ltdesigntester`"
author: "David L Miller"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    fig_caption: yes
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Introduction

`ltdesigntester` is an R package to test basic survey designs and highlight potential issues with using simple estimators (such as Horvitz-Thompson-like estimators; henceforth HT) when animal distribution changes in space.

The package takes a given setup of animal density, design and sighting paramters and generates multiple possible results for a given design. From there a series of different possible models are fitted to the data and relevant statistics recorded.

# Requirements

The following things are required to build a simulation:

  - study area shapefile: defining the area in which the study takes place.
  - density surface: giving "true" the distribution of the animals in the study area.
  - population size: "true" number of animals in the study area.
  - survey design shapefile: the lines to be surveyed, already segmented. Additional list of correspondence of transects to segments is required.
  - detection function definition: describing the detectability and truncation for the survey.
  * stratification scheme: for the HT estimator.

# A simple example



